---
- name: Check if golang exists
  stat:
    path: /usr/local/go/bin/go
  register: go_bin

- name: "Golang | Verify version"
  command: "/usr/local/go/bin/go version"
  register: go_version_output
  changed_when: false
  when: go_bin.stat.exists

- name: Install golang
  get_url:
    url: "{{ go_url }}"
    dest: "/root/build/go-{{ go_version }}.tar.gz"
  register: go_download_result
  become: true
  when: not go_bin.stat.exists or go_version|string not in go_version_output.stdout

- name: Remove old go
  file:
    path: /usr/local/go
    state: absent
  when: go_download_result.state == 'file'

- name: Unarchive go
  unarchive:
    src: "/root/build/go-{{ go_version }}.tar.gz"
    dest: /usr/local
    remote_src: 'yes'
  become: true
  when: go_download_result.state == 'file'

- name: Cleanup
  file:
    path: /root/build
    state: absent
