---
- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ dep_groups }}"
- name: Add users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
  with_items: "{{ users }}"
- name: Add authorized_key entries for each user
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - "authorized_keys"
  ignore_errors: true
